
set_property MARK_DEBUG true [get_nets PacmanWrapper_inst_n_1]
set_property MARK_DEBUG false [get_nets PHY_RXACTIVE]
set_property MARK_DEBUG false [get_nets PHY_RXVALID]
set_property MARK_DEBUG true [get_nets {n_dat[3]}]
set_property MARK_DEBUG true [get_nets {n_dat[2]}]
set_property MARK_DEBUG true [get_nets {n_dat[1]}]
set_property MARK_DEBUG true [get_nets {n_dat[0]}]

set_property MARK_DEBUG false [get_nets {usb_rxdat[0]}]
set_property MARK_DEBUG false [get_nets {usb_rxdat[1]}]
set_property MARK_DEBUG false [get_nets {usb_rxdat[2]}]
set_property MARK_DEBUG false [get_nets {usb_rxdat[3]}]
set_property MARK_DEBUG false [get_nets {usb_rxdat[4]}]
set_property MARK_DEBUG false [get_nets {usb_rxdat[5]}]
set_property MARK_DEBUG false [get_nets {usb_rxdat[6]}]
set_property MARK_DEBUG false [get_nets {usb_rxdat[7]}]
set_property MARK_DEBUG false [get_nets usb_rxval]
set_property MARK_DEBUG false [get_nets ulpi_clk60_IBUF_BUFG]
set_property MARK_DEBUG false [get_nets CLK100MHZ_IBUF_BUFG]
set_property MARK_DEBUG true [get_nets {io_net_result_bits[0]}]
set_property MARK_DEBUG true [get_nets {io_net_result_bits[1]}]
set_property MARK_DEBUG true [get_nets {io_net_result_bits[2]}]
set_property MARK_DEBUG true [get_nets {io_net_result_bits[3]}]
set_property MARK_DEBUG true [get_nets io_net_result_valid]
set_property MARK_DEBUG false [get_nets usb_rxrdy]
set_property MARK_DEBUG true [get_nets PacmanWrapper_inst/AsyncFifo_inst_io_deq_valid]
set_property MARK_DEBUG true [get_nets PacmanWrapper_inst/Pacman_inst/buffer_io_startOut]
connect_debug_port u_ila_0/probe0 [get_nets [list {io_net_result_bits[0]} {io_net_result_bits[1]} {io_net_result_bits[2]} {io_net_result_bits[3]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list io_net_result_valid]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list CLK100MHZ_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {n_dat[0]} {n_dat[1]} {n_dat[2]} {n_dat[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list PacmanWrapper_inst/AsyncFifo_inst_io_deq_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list PacmanWrapper_inst/Pacman_inst/buffer_io_startOut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list n_val]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK100MHZ_IBUF_BUFG]
