# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.cache/wt [current_project]
set_property parent.project_path /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/PacmanWrapper.v
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/DualPortBRAM.v
}
read_vhdl -library xil_defaultlib {
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/usb_utmi/usb_transact.vhdl
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/usb_utmi/usb_packet.vhdl
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/usb_utmi/usb_init.vhdl
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/usb_utmi/usb_control.vhdl
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/usb_utmi/usb_pkg.vhdl
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/usb_utmi/usb_serial.vhdl
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/ulpi_port.vhdl
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.srcs/sources_1/new/SimplisticTest.vhd
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.srcs/sources_1/new/top.vhd
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/src/usb_utmi/usbtest.vhdl
  /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.srcs/sources_1/new/InputBridge.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.srcs/constrs_1/new/constraints.xdc]

read_xdc /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files /home/ulrich/chisel/fpga/usbtest/vivado_proj/ulpi_test/ulpi_test.srcs/constrs_1/new/debug.xdc]


synth_design -top top -part xc7a35tftg256-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
